In [9]:
import pandas as pd
import re
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

# Discovering data

In [12]:
raw_data=pd.read_csv('Data/survey_results_public.csv')
print('my public survey has {} in shape'.format(raw_data.shape))

FileNotFoundError: [Errno 2] No such file or directory: 'Data/survey_results_public.csv'

In [281]:
raw_cop=raw_data.copy()

In [282]:
raw_data.sample(20)

,ResponseId,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
1769,1770,I am a developer by profession,Employed full-time,United States of America,North Carolina,NaN,"Associate degree (A.A., A.S., etc.)",5 - 10 years,Other (please specify):,40,...,45-54 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
73077,73078,I am a developer by profession,Employed full-time,India,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,10,...,35-44 years old,Woman,NaN,NaN,I don't know,None of the above,None of the above,Appropriate in length,Easy,NaN
33785,33786,I am a student who is learning to code,Employed full-time,Bangladesh,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc)",2,...,18-24 years old,Man,No,Bisexual,NaN,None of the above,None of the above,NaN,NaN,NaN
6530,6531,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",35 - 44 years,"Other online resources (ex: videos, blogs, etc...",28,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
21200,21201,I am a developer by profession,Employed full-time,Germany,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",5 - 10 years,Books / Physical media,22,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Too long,Neither easy nor difficult,77831.0
32883,32884,I am a developer by profession,Employed full-time,Romania,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",35 - 44 years,"Other online resources (ex: videos, blogs, etc...",15,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,31212.0
25105,25106,I am a developer by profession,Employed full-time,Switzerland,NaN,NaN,Something else,11 - 17 years,"Other online resources (ex: videos, blogs, etc...",5,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Too short,Easy,55907.0
67631,67632,I am a developer by profession,Employed full-time,India,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",25 - 34 years,Online Courses or Certification,9,...,25-34 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,NaN
18650,18651,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Poland,NaN,NaN,Some college/university study without earning ...,11 - 17 years,Online Forum;Other (please specify):;Books / P...,12,...,25-34 years old,Man,No,Straight / Heterosexual,"White or of European descent;Or, in your own w...",None of the above,None of the above,Appropriate in length,Easy,126550.0
2471,2472,I am a developer by profession,Employed full-time,Poland,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Other (please specify):,20,...,35-44 years old,"Or, in your own words:","Or, in your own words:",Prefer to self-describe:,Prefer not to say,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,57708.0
4961,4962,I am a developer by profession,Employed full-time,"Iran, Islamic Republic of...",NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Online Courses or Certification;Books / Physic...,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,Middle Eastern,None of the above,None of the above,Appropriate in length,NaN,3420.0
76184,76185,I am a developer by profession,Employed full-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,...,18-24 years old,Man,No,Straight / Heterosexual,"Or, in your own words:",NaN,None of the above,Appropriate in length,Easy,NaN
22303,22304,I am a developer by profession,Employed full-time,Brazil,NaN,NaN,Some college/university study without earning ...,5 - 10 years,Books / Physical media,30,...,45-54 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have autism / an autism spectrum disorder (e...,Appropriate in length,Easy,54972.0
29881,29882,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",10,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Too short,Easy,56723.0
13239,13240,I am a student who is learning to code,"Not employed, but looking for work",India,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,"Other online resources (ex: videos, blogs, etc)",2,...,18-24 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,NaN
81378,81379,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Switzerland,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",25 - 34 years,"Other online resources (ex: videos, blogs, etc)",13,...,25-34 years old,Man,No,NaN,NaN,NaN,NaN,Too long,Easy,254122.0
77256,77257,I code primarily as a hobby,Employed full-time,United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc...",8,...,45-54 years old,Man,No,Straight / Heterosexual,"South Asian;Or, in your own words:",None of the above,None of the above,Appropriate in length,Neither easy nor difficult,NaN
33948,33949,I am a developer by profession,Employed full-time,Sweden,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School;Online Courses or Certification;Colleague,9,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,"Or, in your own words:",Appropriate in length,Easy,49092.0
45666,45667,I am a developer by profession,Employed full-time,India,NaN,NaN,Some college/university study without earning ...,11 - 17 years,"Other online resources (ex: videos, blogs, etc...",5,...,18-24 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,I have an anxiety disorder,Appropriate in length,Easy,24014.0
78397,78398,I am a student who is learning to code,"Student, full-time",Indonesia,NaN,NaN,"Secondary school (e.g. American high school, G...",5 - 10 years,Online Forum;Friend or family member;Online Co...,6,...,18-24 years old,Man,No,Bisexual,Southeast Asian,None of the above,I have autism / an autism spectrum disorder (e...,Appropriate in length,Easy,NaN

In [241]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83439 entries, 0 to 83438
Data columns (total 48 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ResponseId                    83439 non-null  int64
 1   MainBranch                    83439 non-null  object
 2   Employment                    83323 non-null  object
 3   Country                       83439 non-null  object
 4   US_State                      14920 non-null  object
 5   UK_Country                    4418 non-null   object
 6   EdLevel                       83126 non-null  object
 7   Age1stCode                    83243 non-null  object
 8   LearnCode                     82963 non-null  object
 9   YearsCode                     81641 non-null  object
 10  YearsCodePro                  61216 non-null  object
 11  DevType                       66484 non-null  object
 12  OrgSize                       60726 non-null  object
 13  Currency                      61080 non-null  object
 14  CompTotal                     47183 non-null  float64
 15  CompFreq                      52150 non-null  object
 16  LanguageHaveWorkedWith        82357 non-null  object
 17  LanguageWantToWorkWith        76821 non-null  object
 18  DatabaseHaveWorkedWith        69546 non-null  object
 19  DatabaseWantToWorkWith        58299 non-null  object
 20  PlatformHaveWorkedWith        52135 non-null  object
 21  PlatformWantToWorkWith        41619 non-null  object
 22  WebframeHaveWorkedWith        61707 non-null  object
 23  WebframeWantToWorkWith        52095 non-null  object
 24  MiscTechHaveWorkedWith        47055 non-null  object
 25  MiscTechWantToWorkWith        38021 non-null  object
 26  ToolsTechHaveWorkedWith       72537 non-null  object
 27  ToolsTechWantToWorkWith       65480 non-null  object
 28  NEWCollabToolsHaveWorkedWith  81234 non-null  object
 29  NEWCollabToolsWantToWorkWith  73022 non-null  object
 30  OpSys                         83294 non-null  object
 31  NEWStuck                      83052 non-null  object
 32  NEWSOSites                    83171 non-null  object
 33  SOVisitFreq                   82413 non-null  object
 34  SOAccount                     82525 non-null  object
 35  SOPartFreq                    67553 non-null  object
 36  SOComm                        82319 non-null  object
 37  NEWOtherComms                 82828 non-null  object
 38  Age                           82407 non-null  object
 39  Gender                        82286 non-null  object
 40  Trans                         80678 non-null  object
 41  Sexuality                     73366 non-null  object
 42  Ethnicity                     79464 non-null  object
 43  Accessibility                 77603 non-null  object
 44  MentalHealth                  76920 non-null  object
 45  SurveyLength                  81711 non-null  object
 46  SurveyEase                    81948 non-null  object
 47  ConvertedCompYearly           46844 non-null  float64
dtypes: float64(2), int64(1), object(45)
memory usage: 30.6+ MB

In [242]:
raw_data.sample(1).iloc[0]

ResponseId                                                                  30545
MainBranch                                         I am a developer by profession
Employment                                                     Employed full-time
Country                                                  United States of America
US_State                                                                 Kentucky
UK_Country                                                                    NaN
EdLevel                              Bachelor’s degree (B.A., B.S., B.Eng., etc.)
Age1stCode                                                          45 - 54 years
LearnCode                                           School;Books / Physical media
YearsCode                                                                      36
YearsCodePro                                                                   32
DevType                         Developer, desktop or enterprise applications;...
OrgSize                                                      100 to 499 employees
Currency                                                USD\tUnited States dollar
CompTotal                                                                120000.0
CompFreq                                                                   Yearly
LanguageHaveWorkedWith                                                     C#;SQL
LanguageWantToWorkWith                                                         C#
DatabaseHaveWorkedWith                                       Microsoft SQL Server
DatabaseWantToWorkWith                                       Microsoft SQL Server
PlatformHaveWorkedWith                                                        NaN
PlatformWantToWorkWith                                                        NaN
WebframeHaveWorkedWith                                                    ASP.NET
WebframeWantToWorkWith                                      ASP.NET;ASP.NET Core
MiscTechHaveWorkedWith                                         .NET Core / .NET 5
MiscTechWantToWorkWith                                 .NET Core / .NET 5;Flutter
ToolsTechHaveWorkedWith                                                       Git
ToolsTechWantToWorkWith                                                   Xamarin
NEWCollabToolsHaveWorkedWith                                        Visual Studio
NEWCollabToolsWantToWorkWith                                        Visual Studio
OpSys                                                                     Windows
NEWStuck                        Visit Stack Overflow;Go for a walk or other ph...
NEWSOSites                                                         Stack Overflow
SOVisitFreq                                   Less than once per month or monthly
SOAccount                                                                     Yes
SOPartFreq                      I have never participated in Q&A on Stack Over...
SOComm                                                             No, not really
NEWOtherComms                                                                  No
Age                                                               45-54 years old
Gender                                                                        Man
Trans                                                                          No
Sexuality                                                 Straight / Heterosexual
Ethnicity                                            White or of European descent
Accessibility                                                   None of the above
MentalHealth                                                    None of the above
SurveyLength                                                Appropriate in length
SurveyEase                                             Neither easy nor difficult
ConvertedCompYearly                                                      120000.0
Name: 30544, dtype: object

### Remarks:
- All our columns are object, <strong>weird!!</strong>

In [243]:
raw_data.describe()

         ResponseId     CompTotal  ConvertedCompYearly
count  83439.000000  4.718300e+04         4.684400e+04
mean   41720.000000  2.119407e+69         1.184262e+05
std    24086.908893  4.603702e+71         5.272944e+05
min        1.000000  0.000000e+00         1.000000e+00
25%    20860.500000  1.600000e+04         2.702500e+04
50%    41720.000000  6.700000e+04         5.621100e+04
75%    62579.500000  1.400000e+05         1.000000e+05
max    83439.000000  1.000000e+74         4.524131e+07

In [244]:
# i can notice that, basicaly we need Age,Age1stCode, LearnCode,YearsCode columns to be numerical
# why they are object

#let's see why 
should_be_num=['Age1stCode','YearsCode','Age','YearsCodePro']

for i in should_be_num:
    print(i)
    print(raw_data[i].unique().tolist())
    print('----------------')

Age1stCode
['18 - 24 years', '11 - 17 years', '5 - 10 years', '25 - 34 years', '35 - 44 years', 'Younger than 5 years', '45 - 54 years', '55 - 64 years', nan, 'Older than 64 years']
----------------
YearsCode
[nan, '7', '17', '3', '4', '6', '16', '12', '15', '10', '40', '9', '26', '14', '39', '20', '8', '19', '5', 'Less than 1 year', '22', '2', '1', '34', '21', '13', '25', '24', '30', '31', '18', '38', 'More than 50 years', '27', '41', '42', '35', '23', '28', '11', '37', '44', '43', '36', '33', '45', '29', '50', '46', '32', '47', '49', '48']
----------------
Age
['25-34 years old', '18-24 years old', '35-44 years old', 'Prefer not to say', '45-54 years old', 'Under 18 years old', '65 years or older', '55-64 years old', nan]
----------------
YearsCodePro
[nan, '10', '4', '5', '6', '2', '30', '9', '18', '12', '21', '1', '16', 'Less than 1 year', '15', '3', '35', '7', '8', '17', '14', '26', '25', '20', '50', '34', '11', '24', '22', '13', '31', '23', '39', '41', '27', '28', '19', '33', 'More than 50 years', '37', '29', '32', '43', '40', '38', '45', '42', '46', '36', '44', '47', '48', '49']
----------------

In [245]:
Dict={
    'YearsCodePro' :{'Less than 1 year':0,'More than 50 years':51},
    'YearsCode':{'More than 50 years':51,'Less than 1 year':0}
}

for i,r in Dict.items():
    raw_cop[i]=raw_cop[i].replace(r).astype(np.float32)

In [246]:
raw_cop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83439 entries, 0 to 83438
Data columns (total 48 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ResponseId                    83439 non-null  int64
 1   MainBranch                    83439 non-null  object
 2   Employment                    83323 non-null  object
 3   Country                       83439 non-null  object
 4   US_State                      14920 non-null  object
 5   UK_Country                    4418 non-null   object
 6   EdLevel                       83126 non-null  object
 7   Age1stCode                    83243 non-null  object
 8   LearnCode                     82963 non-null  object
 9   YearsCode                     81641 non-null  float32
 10  YearsCodePro                  61216 non-null  float32
 11  DevType                       66484 non-null  object
 12  OrgSize                       60726 non-null  object
 13  Currency                      61080 non-null  object
 14  CompTotal                     47183 non-null  float64
 15  CompFreq                      52150 non-null  object
 16  LanguageHaveWorkedWith        82357 non-null  object
 17  LanguageWantToWorkWith        76821 non-null  object
 18  DatabaseHaveWorkedWith        69546 non-null  object
 19  DatabaseWantToWorkWith        58299 non-null  object
 20  PlatformHaveWorkedWith        52135 non-null  object
 21  PlatformWantToWorkWith        41619 non-null  object
 22  WebframeHaveWorkedWith        61707 non-null  object
 23  WebframeWantToWorkWith        52095 non-null  object
 24  MiscTechHaveWorkedWith        47055 non-null  object
 25  MiscTechWantToWorkWith        38021 non-null  object
 26  ToolsTechHaveWorkedWith       72537 non-null  object
 27  ToolsTechWantToWorkWith       65480 non-null  object
 28  NEWCollabToolsHaveWorkedWith  81234 non-null  object
 29  NEWCollabToolsWantToWorkWith  73022 non-null  object
 30  OpSys                         83294 non-null  object
 31  NEWStuck                      83052 non-null  object
 32  NEWSOSites                    83171 non-null  object
 33  SOVisitFreq                   82413 non-null  object
 34  SOAccount                     82525 non-null  object
 35  SOPartFreq                    67553 non-null  object
 36  SOComm                        82319 non-null  object
 37  NEWOtherComms                 82828 non-null  object
 38  Age                           82407 non-null  object
 39  Gender                        82286 non-null  object
 40  Trans                         80678 non-null  object
 41  Sexuality                     73366 non-null  object
 42  Ethnicity                     79464 non-null  object
 43  Accessibility                 77603 non-null  object
 44  MentalHealth                  76920 non-null  object
 45  SurveyLength                  81711 non-null  object
 46  SurveyEase                    81948 non-null  object
 47  ConvertedCompYearly           46844 non-null  float64
dtypes: float32(2), float64(2), int64(1), object(43)
memory usage: 29.9+ MB

In [290]:
object_col=raw_cop.select_dtypes(include='object').columns.to_list()

In [291]:
for c in object_col:
    raw_cop[c]=raw_cop[c].apply(lambda x:x.split(';') if x is not np.nan else [])

In [297]:
i = raw_cop.sample(1).index[0]
print(raw_data['MiscTechHaveWorkedWith'].iloc[i])
print(raw_cop['MiscTechHaveWorkedWith'].iloc[i])

Qt
['Qt']

In [295]:
i = raw_cop.sample(1).index[0]
print(raw_data['DevType'].iloc[i])
print(raw_cop['DevType'].iloc[i])

Developer, back-end;Database administrator;DevOps specialist;Engineering manager;System administrator;Senior Executive (C-Suite, VP, etc.)
['Developer, back-end', 'Database administrator', 'DevOps specialist', 'Engineering manager', 'System administrator', 'Senior Executive (C-Suite, VP, etc.)']

In [299]:
raw_cop.to_pickle('preprocessed_data.pkl')

# Exploratory Data Analysis

## Some Question to discover data


### General :
 - Total number of answers
 - Geographical distributions
 - Missing answers
 
### Skills:
 - Frequency of each skill
 - How are the skill are correlated with each others
 
### Jobs:
- Frequency of each job
- How are the job are correlated with each others

### Relation

- How are the skills are correlated with jobs
- What is the specifity of each skill to a job

In [300]:
raw_cop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83439 entries, 0 to 83438
Data columns (total 48 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ResponseId                    83439 non-null  int64
 1   MainBranch                    83439 non-null  object
 2   Employment                    83439 non-null  object
 3   Country                       83439 non-null  object
 4   US_State                      83439 non-null  object
 5   UK_Country                    83439 non-null  object
 6   EdLevel                       83439 non-null  object
 7   Age1stCode                    83439 non-null  object
 8   LearnCode                     83439 non-null  object
 9   YearsCode                     83439 non-null  object
 10  YearsCodePro                  83439 non-null  object
 11  DevType                       83439 non-null  object
 12  OrgSize                       83439 non-null  object
 13  Currency                      83439 non-null  object
 14  CompTotal                     47183 non-null  float64
 15  CompFreq                      83439 non-null  object
 16  LanguageHaveWorkedWith        83439 non-null  object
 17  LanguageWantToWorkWith        83439 non-null  object
 18  DatabaseHaveWorkedWith        83439 non-null  object
 19  DatabaseWantToWorkWith        83439 non-null  object
 20  PlatformHaveWorkedWith        83439 non-null  object
 21  PlatformWantToWorkWith        83439 non-null  object
 22  WebframeHaveWorkedWith        83439 non-null  object
 23  WebframeWantToWorkWith        83439 non-null  object
 24  MiscTechHaveWorkedWith        83439 non-null  object
 25  MiscTechWantToWorkWith        83439 non-null  object
 26  ToolsTechHaveWorkedWith       83439 non-null  object
 27  ToolsTechWantToWorkWith       83439 non-null  object
 28  NEWCollabToolsHaveWorkedWith  83439 non-null  object
 29  NEWCollabToolsWantToWorkWith  83439 non-null  object
 30  OpSys                         83439 non-null  object
 31  NEWStuck                      83439 non-null  object
 32  NEWSOSites                    83439 non-null  object
 33  SOVisitFreq                   83439 non-null  object
 34  SOAccount                     83439 non-null  object
 35  SOPartFreq                    83439 non-null  object
 36  SOComm                        83439 non-null  object
 37  NEWOtherComms                 83439 non-null  object
 38  Age                           83439 non-null  object
 39  Gender                        83439 non-null  object
 40  Trans                         83439 non-null  object
 41  Sexuality                     83439 non-null  object
 42  Ethnicity                     83439 non-null  object
 43  Accessibility                 83439 non-null  object
 44  MentalHealth                  83439 non-null  object
 45  SurveyLength                  83439 non-null  object
 46  SurveyEase                    83439 non-null  object
 47  ConvertedCompYearly           46844 non-null  float64
dtypes: float64(2), int64(1), object(45)
memory usage: 30.6+ MB

In [301]:
Role_cols=['DevType']
Tech_cols=['LanguageHaveWorkedWith',
          'LanguageWantToWorkWith',
          'DatabaseHaveWorkedWith',
          'PlatformHaveWorkedWith',
          'WebframeHaveWorkedWith',
          'MiscTechHaveWorkedWith',
          'ToolsTechHaveWorkedWith',
          'NEWCollabToolsHaveWorkedWith']

In [308]:
df=pd.read_pickle('.../Documents/GitHub/Talent_tracking/Notebook/preprocessed_data.pkl')
df

FileNotFoundError: [Errno 2] No such file or directory: '.../Documents/GitHub/Talent_tracking/Notebook/preprocessed_data.pkl'